#!/usr/bin/python3

DOMAIN = "sticky"
PATH = "/usr/share/locale"

import os, gettext
from mintcommon import additionalfiles
import subprocess

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

name = _("Notes")
comment = _("Take notes and stay organized")

prefix = "[Desktop Entry]\n"

suffix = """Exec=sticky
Icon=sticky
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;Utility;
StartupNotify=false
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/sticky.desktop", prefix, name, comment, suffix)
